name: Deploy Job Email

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t job-email:latest .

      - name: Stop old container
        run: |
          docker stop job-email || true
          docker rm job-email || true

      - name: Run new container
        run: |
          docker run -d \
            --name job-email \
            --restart unless-stopped \
            -p 3001:3000 \
            job-email:latest
