"""add_job_url_and_source

Revision ID: d1c710afc3ff
Revises: e0b0b269176d
Create Date: 2026-05-24 17:32:41.596931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1c710afc3ff'
down_revision: Union[str, Sequence[str], None] = 'e0b0b269176d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('job_url', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('source', sa.String(), nullable=False, server_default='ai_generated'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'source')
    op.drop_column('applications', 'job_url')
    # ### end Alembic commands ###
